spring:
  application:
    name: task-scheduler-backend
  datasource:
    username: db_user
    password: password
    url: jdbc:postgresql://localhost:5454/task-scheduler-storage
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

server:
  port: 8001

jwt:
  secret: dGhpcyBpcyBhIHN1cGVyIHNlY3JldCBrZXkgZm9yIGp3dA==

kafka:
  topic:
    name: EMAIL_SEN
  email:
    type: WELCOME