spring:
  application:
    name: task-scheduler-backend
  datasource:
    username: db_user
    password: password
    url: jdbc:postgresql://localhost:5454/task-scheduler-storage
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

server:
  port: 8001
